version: '3.8'

services:
  graph-node:
    image: graphprotocol/graph-node:latest
    ports:
      - '8000:8000'   # GraphQL HTTP endpoint
      - '8001:8001'   # GraphQL WebSocket endpoint  
      - '8020:8020'   # JSON-RPC admin endpoint
      - '8030:8030'   # Indexing status endpoint
      - '8040:8040'   # Metrics endpoint
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'hardhat:http://host.docker.internal:8545'
      GRAPH_LOG: info
      GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH: 'true'
    restart: unless-stopped

  ipfs:
    image: ipfs/kubo:latest
    ports:
      - '5001:5001'   # IPFS API
      - '8080:8080'   # IPFS Gateway
    volumes:
      - ipfs_data:/data/ipfs
    environment:
      IPFS_PROFILE: server
    restart: unless-stopped

  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ipfs_data:
  postgres_data: